# Generated by Django 4.2.2 on 2023-07-10 06:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('firebase_uid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='CookBookApp.userprofile')),
                ('likes', models.ManyToManyField(related_name='liked_posts', to='CookBookApp.userprofile')),
                ('saved', models.ManyToManyField(related_name='saved_posts', to='CookBookApp.userprofile')),
                ('shared', models.ManyToManyField(related_name='shared_posts', to='CookBookApp.userprofile')),
            ],
        ),
    ]
