# Generated by Django 4.2.2 on 2023-09-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookBookApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='userId',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='media_files/'),
        ),
    ]
