# Generated by Django 4.2.5 on 2024-02-16 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CookBookApp', '0002_food_receipt_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='CookBookApp.userprofile'),
        ),
    ]
