# Generated by Django 4.2.5 on 2024-02-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookBookApp', '0004_receipt_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='foods',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.AddField(
            model_name='receipt',
            name='foods',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
