# Generated by Django 4.2.5 on 2024-02-16 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CookBookApp', '0005_remove_receipt_user_remove_receipt_foods_delete_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='CookBookApp.userprofile'),
        ),
    ]
