# Generated by Django 4.2.5 on 2024-04-10 06:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CookBookApp', '0006_receipt_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='id',
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
