# Generated by Django 4.2.5 on 2024-04-12 07:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CookBookApp', '0007_remove_receipt_id_receipt_receipt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FridgeDetection',
            fields=[
                ('fridge_detection_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foods', models.JSONField()),
                ('date', models.DateField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridge_detections', to='CookBookApp.userprofile')),
            ],
        ),
    ]
