# Generated by Django 4.2.5 on 2024-04-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookBookApp', '0009_alter_receipt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgedetection',
            name='foods',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
