# Generated by Django 4.2.5 on 2024-04-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookBookApp', '0010_alter_fridgedetection_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgedetection',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
