# Generated by Django 4.2.5 on 2024-04-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CookBookApp', '0012_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='updatedAt',
        ),
    ]
